site_name: BYOC
site_url: https://g4ze.github.io/byoc/
repo_url: https://github.com/g4ze/byoc
site_author: Nilay Gupya

size: { width: 1200, height: 630 }

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt 
  font:
    code: Roboto Mono
  palette:
    scheme: slate
    primary: white