import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Earth3D from "@/components/Earth3D";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative min-h-screen">
          {/* Background Earth3D */}
          <div className="fixed inset-0 z-0">
            <Earth3D />
          </div>
          
          {/* Page content */}
          <main className="relative z-10">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}